#pragma once
#include <windows.h>

#define BGBLACK  0
#define BGDARKBLUE BACKGROUND_BLUE
#define BGDARKGREEN BACKGROUND_GREEN
#define BGDARKCYAN BACKGROUND_GREEN | BACKGROUND_BLUE
#define BGDARKRED BACKGROUND_RED
#define BGDARKMAGENTA BACKGROUND_RED | BACKGROUND_BLUE
#define BGDARKYELLOW BACKGROUND_RED | BACKGROUND_GREEN
#define BGDARKGRAY BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE
#define BGGRAY BACKGROUND_INTENSITY
#define BGBLUE BACKGROUND_INTENSITY | BACKGROUND_BLUE
#define BGGREEN BACKGROUND_INTENSITY | BACKGROUND_GREEN
#define BGCYAN BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE
#define BGRED BACKGROUND_INTENSITY | BACKGROUND_RED
#define BGMAGENTA BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE
#define BGYELLOW BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN
#define BGWHITE BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN |BACKGROUND_BLUE

#define TBLACK  0
#define TDARKBLUE  FOREGROUND_BLUE
#define TDARKGREEN  FOREGROUND_GREEN
#define TDARKCYAN  FOREGROUND_GREEN | FOREGROUND_BLUE
#define TDARKRED  FOREGROUND_RED
#define TDARKMAGENTA  FOREGROUND_RED | FOREGROUND_BLUE
#define TDARKYELLOW  FOREGROUND_RED | FOREGROUND_GREEN
#define TDARKGRAY  FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE
#define TGRAY  FOREGROUND_INTENSITY
#define TBLUE  FOREGROUND_INTENSITY | FOREGROUND_BLUE
#define TGREEN  FOREGROUND_INTENSITY | FOREGROUND_GREEN
#define TCYAN  FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE
#define TRED  FOREGROUND_INTENSITY | FOREGROUND_RED
#define TMAGENTA  FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE
#define TYELLOW  FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN
#define TWHITE  FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE
